Add new Atlanta way property set source to allow walking on trunk roads
ibi-group/OpenTripPlanner pull request #108
Opened 2022-05-20 23:45 UTC by demory

Adds Atlanta-specific OSM way property set source, specifically to allow walking on "trunk" roads which in the Atlanta area are typically major/primary roads that still allow walking and often have bus service. 

To enable, build graph with `"osmWayPropertySet": "atl"` included in build-config.json.

Sample search: walk+transit from 58 Brighton Rd NE in Atlanta to North Avenue MARTA station. With the default way property set, walking is not allowed on Peachtree Rd (a 'trunk' road) and the walk access leg is unnecessarily long/indirect:

![image](https://user-images.githubusercontent.com/653100/169625144-f7026e6a-7941-4eb8-a42f-9c895075a6b7.png)

With the Atlanta property set enabled, walking will be allowed on Peachtree Rd and the walk access leg should be more direct:
<img width="925" alt="image" src="https://user-images.githubusercontent.com/653100/169625025-6569fb69-5b97-4c5a-99e8-bed1f62f234d.png">

2022-05-23 15:55 UTC, leonardehrenfried commented on src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSource.java
> +		} else if ("atl".equals(type)) {
I think `atl` is fine for IBI but if you want to upstream that, then `atlanta` would be clearer. So perhaps you want to call it that already.

2022-05-23 15:56 UTC, leonardehrenfried commented on src/main/java/org/opentripplanner/graph_builder/module/osm/AtlantaWayPropertySetSource.java
> +        props.setProperties("highway=trunk_link", StreetTraversalPermission.ALL, 2.5, 2.5);
Can you add a test like like that? https://github.com/opentripplanner/OpenTripPlanner/blob/9c9dd613489a348d2381acdcbeab8f86589154d7/src/test/java/org/opentripplanner/graph_builder/module/osm/GermanyWayPropertySetSourceTest.java

2022-06-16 08:24 UTC, leonardehrenfried commented
@demory Has asked the following:

>  You’ll see Binh added tests that verify StreetTraversalPermission.ALL permissions for three different ways: a “trunk” way, a “trunk_link” way, and a “secondary” way that should already be walkable and not affected by the changes made by the Atlanta way property set. By default all 3 tests pass as expected.
> As another check, we tried commenting out lines 20-21 in AtlantaWayPropertySetSource.java (which override the trunk/trunk_link defaults), expecting this to cause the first two tests to fail but the third to still pass. However, all three fail in this scenario.
> Do you know why that is? It seems there’s something we don’t understand about how these property sets work.

I investigated a bit and found out that the reason was that the initialization order of the way property set was incorrect. I fixed it in b53fce8d3ab0521a8ba71b55a1be2c0810e1c6b1

What happened here?

Evan introduced a feature where the OSM tags to street permissions lookup was cached: https://github.com/opentripplanner/OpenTripPlanner/pull/3139

However, this features requires you to call `index()` _after_ `populate` because in the indexing phase it is figuring out what all the relevant tag keys in the set are so it can construct cache keys. However, if you call `index()` first and then `populate()` then the set of relevant tag keys is the empty set. This leads to a catastrophic failure where every item would have the same cache key, namely the empty string! Therefore all OSM ways have the same properties!

@demory: These are the sort of things that I meant when I said that the way property set architecture has a great core but the wiring of the components is very awkward and error prone.

2022-06-16 12:06 UTC, binh-dam-ibigroup commented
> I investigated a bit and found out that the reason was that the initialization order of the way property set was incorrect in the test. I fixed it in [b53fce8](https://github.com/ibi-group/OpenTripPlanner/commit/b53fce8d3ab0521a8ba71b55a1be2c0810e1c6b1)

Wow that's a good finding! Thanks for the explanation.

2022-06-21 14:50 UTC, leonardehrenfried requested changes
This looks good but since I keep an eye open for things that would cause problems when upstreaming, I'm thinking that `atl` isn't such a great value for the config property.

2022-06-21 20:24 UTC, demory commented
Thanks @leonardehrenfried, I just committed a change for `atl` -> `atlanta`

2022-06-22 06:08 UTC, leonardehrenfried approved these changes

2022-07-05 18:06 UTC, daniel-heppner-ibigroup approved these changes
Nice work! And cool to see the tests for this.

2022-07-29 14:44 UTC, merged