fix(orca-fares): update and fix WSF fares
ibi-group/OpenTripPlanner pull request #113
Opened 2022-07-06 22:49 UTC by daniel-heppner-ibigroup

To be completed by pull request submitter:

- [ ] **issue**: Link to or create an [issue](https://github.com/opentripplanner/OpenTripPlanner/issues) that describes the relevant feature or bug. Add [GitHub keywords](https://help.github.com/articles/closing-issues-using-keywords/) to this PR's description (e.g., `closes #45`).
- [ ] **roadmap**: Check the [roadmap](https://github.com/orgs/opentripplanner/projects/1) for this feature or bug. If it is not already on the roadmap, PLC will discuss as part of the review process.
- [ ] **tests**: Have you added relevant test coverage? Are all the tests passing on [the continuous integration service (Travis CI)](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Developers-Guide.md#continuous-integration)?
- [ ] **formatting**: Have you followed the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Developers-Guide.md#code-style)? 
- [ ] **documentation**: If you are adding a new configuration option, have you added an explanation to the [configuration documentation](docs/Configuration.md) tables and sections?
- [ ] **changelog**: add a bullet point to the [changelog file](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Changelog.md) with description and link to the linked issue

To be completed by @opentripplanner/plc:

- [ ] reviews and approvals by 2 members, ideally from different organizations
- [ ] **after merging**: update the relevant card on the [roadmap](https://github.com/orgs/opentripplanner/projects/1)

2022-07-07 14:13 UTC, binh-dam-ibigroup commented on src/main/java/org/opentripplanner/routing/impl/OrcaFareServiceImpl.java
>              case PIERCE_COUNTY_TRANSIT:
Is Pierce County using the same fare as the ferry?

2022-07-07 14:15 UTC, binh-dam-ibigroup commented on src/main/java/org/opentripplanner/routing/impl/OrcaFareServiceImpl.java
> +        // WSF is free in one direction on each route
Could you add a comment explaining how the free direction is determined?

2022-07-07 14:23 UTC, binh-dam-ibigroup commented on src/main/java/org/opentripplanner/routing/impl/OrcaFareServiceImpl.java
>              case PIERCE_COUNTY_TRANSIT:
Coupeville-PortTownsend seems to be the exception.

2022-07-07 14:26 UTC, binh-dam-ibigroup approved these changes
Conditional approval on fixing the Pierce Transit fare and adding a comment regarding the fare-free direction.

2022-07-07 14:31 UTC, binh-dam-ibigroup requested changes
Sorry @daniel-heppner-ibigroup, could you also fix the tests and update the PR description, please?

2022-07-07 16:57 UTC, daniel-heppner-ibigroup commented on src/main/java/org/opentripplanner/routing/impl/OrcaFareServiceImpl.java
>              case PIERCE_COUNTY_TRANSIT:
Good catch!

2022-07-07 17:51 UTC, binh-dam-ibigroup approved these changes
LGTM

2022-07-08 19:55 UTC, philip-cline approved these changes

2022-07-08 23:07 UTC, merged