Graph builder improvements
ibi-group/OpenTripPlanner pull request #27
Opened 2020-02-06 07:58 UTC by evansiroky

This PR does the following:

- Removes the BusRouteStreetMatcher graph builder and associated classes/vars since they no longer have any effect on the resulting graph that is built. See https://github.com/opentripplanner/OpenTripPlanner/issues/2957.
- Refactors all graph builder buildGraph calls to use GraphBuilderModuleSummaries. These summaries can be used to improve logging and reporting of various graph build modules.
- Improves the report that is written when annotations and graph build stats are enabled (the build-config.json must have the `htmlAnnotations` set to `true`).

2020-02-10 16:21 UTC, binh-dam-ibigroup requested changes
Only one minor change! Thanks.

2020-02-10 16:21 UTC, binh-dam-ibigroup commented on src/test/java/org/opentripplanner/graph_builder/module/GtfsGraphBuilderModuleTest.java
>      private GtfsModule builder;
Variable `builder` should be declared inside each test (it is assigned in each test each time).

2020-02-10 21:13 UTC, evansiroky commented
Just added a few more subtask reporters and made the change @binh-dam-ibigroup suggested.

2020-02-10 23:26 UTC, binh-dam-ibigroup approved these changes

2020-02-11 20:04 UTC, landonreed requested changes
As discussed on the team call, please add the commands to kick off the build and attach data inputs for the Portland area we're using for testing this PR and future elevation improvement PRs. Thanks!

2020-02-22 00:03 UTC, evansiroky commented
Details shared on our company chat.

2020-02-25 16:09 UTC, landonreed approved these changes

2020-02-25 16:09 UTC, merged