Lazy-create thread-specific coverage to immediately process cached edges
ibi-group/OpenTripPlanner pull request #30
Opened 2020-03-16 23:01 UTC by evansiroky

Add one more small improvement that should speed-up calculations during builds that use cached elevations.

2020-03-17 12:41 UTC, landonreed commented on src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
> +     * @param edgeGeomerty The geometry of the edge
typo `edgeGeomerty`

2020-03-17 14:40 UTC, binh-dam-ibigroup requested changes
Please see extract method request.

2020-03-17 14:40 UTC, binh-dam-ibigroup commented on src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
> +            }
Extract into its own method.

2020-03-17 23:11 UTC, evansiroky commented
Moved some stuff around, hopefully it looks better now.

2020-03-18 21:50 UTC, binh-dam-ibigroup submitted a review, later dismissed

2020-03-26 20:47 UTC, landonreed commented on src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
> + * THIS CLASS IS MULTI-THEARED
haha typo. Of course it's practically on the first line 😜

2020-03-26 20:51 UTC, landonreed commented on src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
> +         * avoid other threads waiting for a lock to be released on the Coverage instance. This concurrent HashMap will
There is no longer a Concurrent HashMap, right?

2020-03-30 14:59 UTC, landonreed submitted a review, later dismissed

2020-04-03 02:39 UTC, evansiroky commented
Just added some more code that turns off this multi-threading stuff by default and only activates it when a user sets the `elevationModuleParallelism` in build-config.json to a value greater than 1.

2020-04-06 21:13 UTC, binh-dam-ibigroup approved these changes
Amazing.

2020-05-01 17:54 UTC, landonreed approved these changes

2020-05-01 17:55 UTC, landonreed commented
@evansiroky, nice work!

2020-05-01 19:50 UTC, merged