Assign feed id alphabetically
ibi-group/OpenTripPlanner pull request #31
Opened 2020-03-31 17:29 UTC by landonreed

Handle assignment of feed IDs in a systematic (i.e., alphabetical) fashion. This at least allows us to predict how the feed IDs will be assigned based on the input zip file names.

2020-04-01 05:02 UTC, evansiroky requested changes
There's a PR over here for the main OTP repo that'll do this: https://github.com/opentripplanner/OpenTripPlanner/pull/3022. I am leaning towards cherry-picking from that PR due to broader community support and so that our repo aligns with the OTP repo.

2020-04-02 20:20 UTC, binh-dam-ibigroup approved these changes

2020-04-21 19:38 UTC, landonreed commented
Yea, I think their approach to disregard the file path probably makes a little more sense.

2020-04-21 19:38 UTC, closed without merging

2020-05-07 19:43 UTC, landonreed commented
@evansiroky, if you're in favor of opentripplanner#3022, could you go ahead and provide a review?