Do not create transfers to stops that don't allow boardings
ibi-group/OpenTripPlanner pull request #32
Opened 2020-03-31 19:25 UTC by evansiroky

This adds a some code that will not create transfers to a stop on a stop pattern if all of the stop times associated with that stop don't allow boardings.

Fixes https://github.com/ibi-group/trimet-mod-otp/issues/258

2020-03-31 19:29 UTC, binh-dam-ibigroup approved these changes

2020-03-31 20:52 UTC, landonreed commented on src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
> +                // FIXME: this below check will only work for feeds that where all trips associated with a certain
typo: remove `that`

2020-03-31 20:55 UTC, landonreed requested changes
Just a minor typo that needs fixing. Is there any way we can fix the issue you've noted while we're at it?

2020-04-01 23:38 UTC, evansiroky commented
Well, it turns out the fix I was recommending in the FIXME already exists!

2020-04-02 17:17 UTC, landonreed approved these changes

2020-04-02 20:07 UTC, binh-dam-ibigroup approved these changes

2020-04-02 23:10 UTC, merged

2020-04-11 03:55 UTC, fpurcell commented
Hey Evan ... low-priority, but when you're back in the office, can you look into the following:

a) has Uber changed config somewhere along the way from 84becf34972705d20914ca6c9fb009bd48fb991b to 97183029aa030a0e92c93747927a2151fa2b2629
b) this config https://maps.trimet.org/m/router-config.json plans Uber trips using this graph version: 84becf34972705d20914ca6c9fb009bd48fb991b
c) but version 97183029aa030a0e92c93747927a2151fa2b2629 no longer plans Uber trips (it does plan BIKETOWN and e-scooter trips tho)
d) didn't have time to capture any logging with the broken graph ... but I could if need be