Refactor drive-time reluctance factors
ibi-group/OpenTripPlanner pull request #51
Opened 2021-02-05 20:39 UTC by evansiroky

This refactors the application of drive time reluctance factors in a number of ways.

Previously, the drive time reluctance factors only applied to the CAR_HAIL and CAR_RENT modes. Furthermore, they were hard-coded and overrode any default configurations set in the `router-config.json` file.

This changes it so that these factors are not overwritten to hardcoded values and furthermore, makes it possible to change these factors on a per-request basis. This breaks some configuration as it will now be required to either modify the `router-config.json` file to include the defaults or change whatever program that is calling the OTP API to send in query parameters on a per-request basis.

2021-02-08 16:29 UTC, br648 reviewed
The update seems straight forward enough. I was just wondering if it requires any unit tests e.g providing these values in a request or updating router-config.json?

2021-02-09 21:37 UTC, binh-dam-ibigroup approved these changes
After playing a bit with this, passing different drive reluctance parameters to OTP queries seem to change results involving car modes.

2021-02-10 18:54 UTC, landonreed requested changes
I think my only concern is how abstracted the comments for these items are. They could:
- offer values that are useful to improve P&R results (maybe with the caveat of what region was being tested)
- describe the added "weight" a little more concretely.

2021-02-23 07:31 UTC, evansiroky commented
> I think my only concern is how abstracted the comments for these items are. They could:
> 
> * offer values that are useful to improve P&R results (maybe with the caveat of what region was being tested)
> * describe the added "weight" a little more concretely.

See latest commit

2021-02-23 16:19 UTC, landonreed approved these changes

2021-02-23 16:20 UTC, landonreed commented
@evansiroky, those comments look great. Do we need to update any config files before merging into `ibi-dev`?

2021-02-26 22:42 UTC, evansiroky commented
> @evansiroky, those comments look great. Do we need to update any config files before merging into `ibi-dev`? Also, should we let TriMet know about any config changes needed in this new version?

I don't believe we have any deployments that would be affected by this change, since the only change that would be seen would be to CAR_RENT or CAR_HAIL queries at this time. We should eventually update the router-config files to have good values, but merging this PR is the first step. I have alerted @fpurcell about this change, so I'm going to merge now.

2021-02-26 22:42 UTC, merged